=== RaresI/HW1---SeWeb/data/recipes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:simpleType name="CuisineType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Italian"/>
            <xs:enumeration value="Asian"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DifficultyLevel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Easy"/>
            <xs:enumeration value="Medium"/>
            <xs:enumeration value="Hard"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RecipeId">
        <xs:restriction base="xs:string">
            <xs:pattern value="r[0-9]{2,}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="recipes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recipe" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="NonEmptyString"/>
                            <xs:element name="cuisine" type="CuisineType"/>
                            <xs:element name="difficulty" type="DifficultyLevel"/>
                            <xs:element name="source" type="NonEmptyString" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="RecipeId" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueRecipeId">
            <xs:selector xpath="recipe"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== RaresI/HW1---SeWeb/data/recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="recipes.xsd">
  <recipe id="r01">
    <title>Creamy pumpkin pasta</title>
    <cuisine>Asian</cuisine>
    <difficulty>Hard</difficulty>
    <source>creamy-pumpkin-pasta</source>
  </recipe>
  <recipe id="r02">
    <title>Sausage, mustard &amp; apple hash</title>
    <cuisine>Italian</cuisine>
    <difficulty>Hard</difficulty>
    <source>sausage-mustard-apple-hash</source>
  </recipe>
  <recipe id="r03">
    <title>Mushroom stroganoff</title>
    <cuisine>Asian</cuisine>
    <difficulty>Hard</difficulty>
    <source>mushroom-stroganoff</source>
  </recipe>
  <recipe id="r04">
    <title>Beetroot &amp; feta pasta</title>
    <cuisine>Asian</cuisine>
    <difficulty>Easy</difficulty>
    <source>beetroot-feta-pasta</source>
  </recipe>
  <recipe id="r05">
    <title>Pork &amp; apple burgers</title>
    <cuisine>Asian</cuisine>
    <difficulty>Medium</difficulty>
    <source>pork-apple-burgers</source>
  </recipe>
  <recipe id="r06">
    <title>Mushroom soup</title>
    <cuisine>Italian</cuisine>
    <difficulty>Medium</difficulty>
    <source>mushroom-soup</source>
  </recipe>
  <recipe id="r07">
    <title>Squash &amp; halloumi flatbreads with sweet chilli beetroot jam</title>
    <cuisine>Italian</cuisine>
    <difficulty>Easy</difficulty>
    <source>squash-halloumi-flatbreads-with-sweet-chilli-beetroot-jam</source>
  </recipe>
  <recipe id="r08">
    <title>Simple squash risotto</title>
    <cuisine>Asian</cuisine>
    <difficulty>Hard</difficulty>
    <source>simple-squash-risotto</source>
  </recipe>
  <recipe id="r09">
    <title>Slow cooker spiced root &amp; lentil casserole</title>
    <cuisine>Asian</cuisine>
    <difficulty>Hard</difficulty>
    <source>slow-cooker-spiced-root-lentil-casserole</source>
  </recipe>
  <recipe id="r10">
    <title>Squash &amp; spinach fusilli with pecans</title>
    <cuisine>Italian</cuisine>
    <difficulty>Medium</difficulty>
    <source>squash-spinach-fusilli-pecans</source>
  </recipe>
  <recipe id="r11">
    <title>Easy vegetable curry</title>
    <cuisine>Asian</cuisine>
    <difficulty>Medium</difficulty>
    <source>vegetable-curry-crowd</source>
  </recipe>
  <recipe id="r12">
    <title>Sausage &amp; butternut squash shells</title>
    <cuisine>Italian</cuisine>
    <difficulty>Medium</difficulty>
    <source>sausage-butternut-squash-shells</source>
  </recipe>
  <recipe id="r13">
    <title>Autumn vegetable soup with cheesy toasts</title>
    <cuisine>Asian</cuisine>
    <difficulty>Medium</difficulty>
    <source>autumn-vegetable-soup-cheesy-toasts</source>
  </recipe>
  <recipe id="r14">
    <title>Mushroom &amp; sausage pasta</title>
    <cuisine>Asian</cuisine>
    <difficulty>Easy</difficulty>
    <source>mushroom-sausage-pasta</source>
  </recipe>
  <recipe id="r15">
    <title>Creamy pumpkin &amp; lentil soup</title>
    <cuisine>Italian</cuisine>
    <difficulty>Hard</difficulty>
    <source>creamy-pumpkin-lentil-soup</source>
  </recipe>
  <recipe id="r16">
    <title>Curried parsnip soup</title>
    <cuisine>Italian</cuisine>
    <difficulty>Easy</difficulty>
    <source>spiced-parsnip-soup</source>
  </recipe>
  <recipe id="r17">
    <title>Red onion gravy</title>
    <cuisine>Italian</cuisine>
    <difficulty>Hard</difficulty>
    <source>red-onion-gravy</source>
  </recipe>
  <recipe id="r18">
    <title>Butternut squash pilaf</title>
    <cuisine>Italian</cuisine>
    <difficulty>Hard</difficulty>
    <source>butternut-squash-pilaf</source>
  </recipe>
  <recipe id="r19">
    <title>Sausage &amp; maple swede traybake</title>
    <cuisine>Italian</cuisine>
    <difficulty>Medium</difficulty>
    <source>sausage-maple-swede-traybake</source>
  </recipe>
  <recipe id="r20">
    <title>Cauliflower mac &amp; cheese</title>
    <cuisine>Italian</cuisine>
    <difficulty>Hard</difficulty>
    <source>cauliflower-mac-cheese</source>
  </recipe>
  <recipe id="r21">
    <title>Mustardy pork &amp; apples</title>
    <cuisine>Italian</cuisine>
    <difficulty>Medium</difficulty>
    <source>mustardy-pork-apples</source>
  </recipe>
</recipes>
